<a href="https://colab.research.google.com/github/Krishnasindhu23/ML_Classification_projects/blob/main/Iris_Classification_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from  sklearn import  datasets
iris=datasets.load_iris()
print(list(iris.target_names))

['setosa', 'versicolor', 'virginica']


In [ ]:
x=iris.data
y=iris.target
#print(type(y))

<class 'numpy.ndarray'>


In [ ]:
for i,j in zip(x,y):
  if j==0:
    j='setosa'
  elif j==1:
    j='versicolor'
  else:
    j='virginica'
  print(i,j)

[5.1 3.5 1.4 0.2] setosa
[4.9 3.  1.4 0.2] setosa
[4.7 3.2 1.3 0.2] setosa
[4.6 3.1 1.5 0.2] setosa
[5.  3.6 1.4 0.2] setosa
[5.4 3.9 1.7 0.4] setosa
[4.6 3.4 1.4 0.3] setosa
[5.  3.4 1.5 0.2] setosa
[4.4 2.9 1.4 0.2] setosa
[4.9 3.1 1.5 0.1] setosa
[5.4 3.7 1.5 0.2] setosa
[4.8 3.4 1.6 0.2] setosa
[4.8 3.  1.4 0.1] setosa
[4.3 3.  1.1 0.1] setosa
[5.8 4.  1.2 0.2] setosa
[5.7 4.4 1.5 0.4] setosa
[5.4 3.9 1.3 0.4] setosa
[5.1 3.5 1.4 0.3] setosa
[5.7 3.8 1.7 0.3] setosa
[5.1 3.8 1.5 0.3] setosa
[5.4 3.4 1.7 0.2] setosa
[5.1 3.7 1.5 0.4] setosa
[4.6 3.6 1.  0.2] setosa
[5.1 3.3 1.7 0.5] setosa
[4.8 3.4 1.9 0.2] setosa
[5.  3.  1.6 0.2] setosa
[5.  3.4 1.6 0.4] setosa
[5.2 3.5 1.5 0.2] setosa
[5.2 3.4 1.4 0.2] setosa
[4.7 3.2 1.6 0.2] setosa
[4.8 3.1 1.6 0.2] setosa
[5.4 3.4 1.5 0.4] setosa
[5.2 4.1 1.5 0.1] setosa
[5.5 4.2 1.4 0.2] setosa
[4.9 3.1 1.5 0.2] setosa
[5.  3.2 1.2 0.2] setosa
[5.5 3.5 1.3 0.2] setosa
[4.9 3.6 1.4 0.1] setosa
[4.4 3.  1.3 0.2] setosa
[5.1 3.4 1.5 0.2] setosa


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.5)

In [ ]:
from sklearn import tree
classifier=tree.DecisionTreeClassifier()

In [ ]:
classifier.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
predictions=classifier.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,predictions))

0.8933333333333333


In [ ]:
#Using KNeighboursClassifier
from sklearn import neighbors
cl=neighbors.KNeighborsClassifier()

In [ ]:
cl.fit(x_train,y_train)
predictions=cl.predict(x_test)
print(accuracy_score(y_test,predictions))

0.9333333333333333


In [37]:
!git clone https://github.com/Krishnasindhu23/ML_Classification_projects.git


Cloning into 'ML_Classification_projects'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
